# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
                ('subject', models.CharField(max_length=20, verbose_name='aim')),
                ('message', models.TextField(verbose_name='Confess')),
            ],
        ),
    ]
